import pandas as pd
import matplotlib.pyplot as plt

bt = pd.read_csv("bubble_time.csv",header=None)
bc = pd.read_csv("bubble_comp.csv",header=None)
st = pd.read_csv("selection_time.csv",header=None)
sc = pd.read_csv("selection_comp.csv",header=None)
mt = pd.read_csv("merge_time.csv",header=None)
mc = pd.read_csv("merge_comp.csv",header=None)
qt = pd.read_csv("quick_time.csv",header=None)
qc = pd.read_csv("quick_comp.csv",header=None)

fig, axes = plt.subplots(nrows=1, ncols=1, figsize=(20, 12))
axes.get_xaxis().get_major_formatter().set_scientific(False)
axes.get_yaxis().get_major_formatter().set_scientific(False)
axes.set_xticks([i for i in range(100000,1000001,50000)])
axes.plot(bt[0],bt[1],marker='o',label = "bubble sort")
axes.plot(st[0],st[1],marker='o',label = "selection sort")
axes.plot(mt[0],mt[1],marker='s',label = "merge sort")
axes.plot(qt[0],qt[1],label = "quick sort",alpha=0.7)
plt.title("Size of array versus time taken for sorting",fontsize=20,fontweight='bold')
plt.xlabel("SIZE",fontsize=15,fontweight='bold')
plt.ylabel("TIME (in seconds)",fontsize=15,fontweight='bold')
plt.grid()
plt.legend()
plt.show()
fig, axes = plt.subplots(nrows=1, ncols=1, figsize=(20, 12))
axes.get_xaxis().get_major_formatter().set_scientific(False)
axes.get_yaxis().get_major_formatter().set_scientific(False)
axes.set_xticks([i for i in range(100000,1000001,50000)])
axes.plot(bc[0],bc[1],marker="v",label = "bubble sort")
axes.plot(sc[0],sc[1],marker="^",label = "selection sort",alpha=0.7)
axes.plot(mc[0],mc[1],marker="v",label = "merge sort")
axes.plot(qc[0],qc[1],marker="^",label = "quick sort",alpha=0.7)
plt.title("Size of array versus number of comparisons made",fontsize=20,fontweight='bold')
plt.xlabel("SIZE",fontsize=15,fontweight='bold')
plt.ylabel("COMPARISONS",fontsize=15,fontweight='bold')
plt.grid()
plt.legend()
plt.show()